### To check on the current situation of the dataset 
- duplicates
- missing values
- data formatting,...)

In [3]:
import pandas as pd
df = pd.read_csv("../data/mobile_game_inapp_purchases.csv")

In [4]:
# Data Quality Audit
df["UserID"].duplicated().sum() 
# No duplicate UserIDs, 3,024 players in the dataset.

np.int64(0)

In [5]:
df.isnull().sum()

UserID                             0
Age                               60
Gender                            60
Country                           60
Device                            60
GameGenre                         60
SessionCount                       0
AverageSessionLength               0
SpendingSegment                    0
InAppPurchaseAmount              136
FirstPurchaseDaysAfterInstall    136
PaymentMethod                    136
LastPurchaseDate                 136
dtype: int64

#### 60 values missing in the player demographics, platform information columns.
#### 136 values missing in the purchase information columns.

In [6]:
# Does a player with missing purchase information also have missing demographic information?
missing_purchase_information = df[df["InAppPurchaseAmount"].isnull()][["UserID", "Age", "Gender", "Country", "Device", "GameGenre", "SessionCount", "SpendingSegment", "InAppPurchaseAmount", "FirstPurchaseDaysAfterInstall", "PaymentMethod", "LastPurchaseDate"]].head(10)

missing_purchase_information

,UserID,Age,Gender,Country,Device,GameGenre,SessionCount,SpendingSegment,InAppPurchaseAmount,FirstPurchaseDaysAfterInstall,PaymentMethod,LastPurchaseDate
11,a516f724-6b0f-438c-b20b-59f5f35ab06a,31.0,Male,Sweden,Android,Simulation,10,Dolphin,NaN,NaN,NaN,NaN
31,2868c7dc-a4bc-4143-8256-334e29ec7458,54.0,Female,USA,Android,Sandbox,13,Minnow,NaN,NaN,NaN,NaN
43,daa87ce2-9524-437b-96f5-d862e44ba2a6,20.0,Female,Egypt,iOS,Adventure,12,Minnow,NaN,NaN,NaN,NaN
50,9c3598c6-6cd4-4da2-81ed-a8053987aa80,33.0,Female,Japan,Android,Fighting,12,Minnow,NaN,NaN,NaN,NaN
78,d88da455-eacb-4fc0-b7d8-9ee22f1c0ffa,18.0,Male,Saudi Arabia,Android,Fighting,6,Minnow,NaN,NaN,NaN,NaN
81,55b14ef0-9383-48b5-9e88-b5814331b23d,NaN,Female,UK,iOS,Puzzle,12,Minnow,NaN,NaN,NaN,NaN
113,ea67c7b3-f672-4d1f-a87c-b6ad687805d7,52.0,Male,Mexico,iOS,MOBA,13,Minnow,NaN,NaN,NaN,NaN
117,d4cb7f92-952d-4528-b4bb-96d4a9bd038a,37.0,Male,Italy,NaN,Strategy,9,Minnow,NaN,NaN,NaN,NaN
122,1f582143-b515-493b-86c9-8a36fedffabe,25.0,Female,USA,Android,Puzzle,9,Minnow,NaN,NaN,NaN,NaN
124,f952dd17-61b1-4f47-a01f-19e66d0b84dc,40.0,Female,Sweden,iOS,Fighting,10,Dolphin,NaN,NaN,NaN,NaN

In [7]:
df[df["InAppPurchaseAmount"].isnull()]["SpendingSegment"].value_counts(dropna=False)

SpendingSegment
Minnow     111
Dolphin     20
Whale        5
Name: count, dtype: int64

#### **136 players don't have purchase information.** 
#### Since they don't have any records on the purchase, but they are still segmented, meaning that we just don't have their purchase behavior data, yet, they should not be assumed to have zero-spending.
#### With this assumption, we can either: (1) impute the missing values to better do the purchase-behavior analysis, or (2) exclude them from the analyses.
#### Only 136 out of more than 3k units, which is only a small percentage. Therefore, to avoid complications in our analysis, we can omit these players from the analysis of purchase behavior.

In [8]:
df[df["Age"].isnull()][
    ["UserID", "Age", "Gender", "Country", "Device", "GameGenre"]
].head(10)

,UserID,Age,Gender,Country,Device,GameGenre
29,0d4f2cd8-6cee-4133-8cb2-435a0f6d19ef,NaN,Female,Russia,iOS,Sandbox
81,55b14ef0-9383-48b5-9e88-b5814331b23d,NaN,Female,UK,iOS,Puzzle
84,523abcfa-4d38-4a89-b5f5-ce5e4f215fcf,NaN,Male,Bangladesh,iOS,MMORPG
165,bcb6e14f-1ff4-4d64-bf00-d41fd29961ad,NaN,Female,Brazil,Android,Strategy
188,bd726fee-fde2-4063-8532-3f16aa8e2a56,NaN,Male,Afghanistan,iOS,Adventure
277,0d15b643-977d-4ec4-9599-7c59b5ee3e73,NaN,Female,Mexico,Android,Casual
323,6cd4c758-a652-4e83-baf6-d7621b6c8157,NaN,Male,NaN,iOS,Action RPG
332,f8adc2ad-7135-4a6c-b799-faf0ad499618,NaN,Female,India,Android,Puzzle
352,d05c69a0-f919-496f-97d7-85ad834cdd38,NaN,Female,Canada,Android,Simulation
385,dd9ca908-f190-4b59-883c-c6d7f8ae9d6a,NaN,Female,Australia,iOS,Puzzle

In [9]:
df["Age"].isnull().sum()

np.int64(60)

#### Needed to check if 60 missing values in the demographic information are information of the same 60 players. 
#### Turned out it's a No. 
#### Therefore, keep these columns with missing values intact. Only when doing analysis in separate piece of information, we can drop the missing values in that column.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         3024 non-null   object
 1   Age                            2964 non-null   float64
 2   Gender                         2964 non-null   object
 3   Country                        2964 non-null   object
 4   Device                         2964 non-null   object
 5   GameGenre                      2964 non-null   object
 6   SessionCount                   3024 non-null   int64
 7   AverageSessionLength           3024 non-null   float64
 8   SpendingSegment                3024 non-null   object
 9   InAppPurchaseAmount            2888 non-null   float64
 10  FirstPurchaseDaysAfterInstall  2888 non-null   float64
 11  PaymentMethod                  2888 non-null   object
 12  LastPurchaseDate               2888 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 307.2+ KB

In [11]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
UserID,3024,3024,c9889ab0-9cfc-4a75-acd9-5eab1df0015c,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,2964.0,NaN,NaN,NaN,33.533738,11.992258,13.0,23.0,33.0,44.0,54.0
Gender,2964,3,Male,1810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,2964,27,India,242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Device,2964,2,Android,1738,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GameGenre,2964,15,Simulation,219,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SessionCount,3024.0,NaN,NaN,NaN,10.074735,3.115863,1.0,8.0,10.0,12.0,22.0
AverageSessionLength,3024.0,NaN,NaN,NaN,20.073978,8.585208,5.01,12.68,20.315,27.42,34.99
SpendingSegment,3024,3,Minnow,2544,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InAppPurchaseAmount,2888.0,NaN,NaN,NaN,102.582864,454.339708,0.0,5.9875,11.975,17.7625,4964.45
FirstPurchaseDaysAfterInstall,2888.0,NaN,NaN,NaN,15.384003,8.946191,0.0,8.0,16.0,23.0,30.0
PaymentMethod,2888,7,Debit Card,433,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LastPurchaseDate,2888,225,2025-05-31,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
print("IAP = 0:", (df["InAppPurchaseAmount"] == 0).sum())

print("\nSpendingSegment among IAP = 0:")
print(df[df["InAppPurchaseAmount"] == 0]["SpendingSegment"].value_counts(dropna=False))

print("\nInvalid Age:")
print(((df["Age"] < 13) | (df["Age"] > 100)).sum())

print("\nInvalid SessionCount:")
print((df["SessionCount"] <= 0).sum())

print("\nInvalid AverageSessionLength:")
print((df["AverageSessionLength"] <= 0).sum())

print("\nInvalid FirstPurchaseDaysAfterInstall:")
print((df["FirstPurchaseDaysAfterInstall"] < 0).sum())

IAP = 0: 1

SpendingSegment among IAP = 0:
SpendingSegment
Minnow    1
Name: count, dtype: int64

Invalid Age:
0

Invalid SessionCount:
0

Invalid AverageSessionLength:
0

Invalid FirstPurchaseDaysAfterInstall:
0

#### There are no invalid values in all columns.
#### What's left is to change the dtype of the "LastPurchaseDate" column.

In [13]:
parsed_dates = pd.to_datetime(df["LastPurchaseDate"], errors='coerce')
print("\nInvalid LastPurchaseDate:", parsed_dates.isna().sum())
print("Min date:", parsed_dates.min())
print("Max date:", parsed_dates.max())

Invalid LastPurchaseDate: 136
Min date: 2025-01-01 00:00:00
Max date: 2025-08-13 00:00:00

In [22]:
df["LastPurchaseDate"] = pd.to_datetime(df["LastPurchaseDate"])
df["LastPurchaseDate"].dtype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         3024 non-null   object
 1   Age                            2964 non-null   float64
 2   Gender                         2964 non-null   object
 3   Country                        2964 non-null   object
 4   Device                         2964 non-null   object
 5   GameGenre                      2964 non-null   object
 6   SessionCount                   3024 non-null   int64
 7   AverageSessionLength           3024 non-null   float64
 8   SpendingSegment                3024 non-null   object
 9   InAppPurchaseAmount            2888 non-null   float64
 10  FirstPurchaseDaysAfterInstall  2888 non-null   float64
 11  PaymentMethod                  2888 non-null   object
 12  LastPurchaseDate               2888 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 307.2+ KB

In [15]:
# Check the value counts of categorical columns
categorical_cols = [
    "Gender",
    "Country",
    "Device",
    "GameGenre",
    "SpendingSegment",
    "PaymentMethod"
]
for col in categorical_cols:
    print(f"\n{col} value counts:")
    print(df[col].value_counts(dropna=False))

Gender value counts:
Gender
Male      1810
Female    1098
NaN         60
Other       56
Name: count, dtype: int64

Country value counts:
Country
India           242
Switzerland     119
Saudi Arabia    116
Mexico          115
Germany         114
Netherlands     114
Australia       113
Italy           112
Japan           112
UK              108
Norway          107
USA             107
Denmark         106
Sweden          106
Brazil          105
Iran            105
Canada          105
South Korea     103
Egypt           101
Bangladesh      101
China           101
Spain            96
Russia           93
Afghanistan      93
France           92
Turkey           90
Sri Lanka        88
NaN              60
Name: count, dtype: int64

Device value counts:
Device
Android    1738
iOS        1226
NaN          60
Name: count, dtype: int64

GameGenre value counts:
GameGenre
Simulation       219
Sandbox          219
Sports           217
Casual           209
Puzzle           206
Card             202
MMORPG           198
Strategy         198
Role Playing     193
Action RPG       191
Racing           191
Battle Royale    189
Fighting         181
MOBA             181
Adventure        170
NaN               60
Name: count, dtype: int64

SpendingSegment value counts:
SpendingSegment
Minnow     2544
Dolphin     412
Whale        68
Name: count, dtype: int64

PaymentMethod value counts:
PaymentMethod
Debit Card         433
Google Pay         431
Gift Card          422
Carrier Billing    417
Credit Card        410
Paypal             401
Apple Pay          374
NaN                136
Name: count, dtype: int64

### To check the cleaned version of the dataset

In [16]:
df_clean = df.copy()
df_clean.shape

(3024, 13)

In [17]:
# Cleaning the missing values
demographic_cols = [
    "Age",
    "Gender",
    "Country",
    "Device",
    "GameGenre"
]

purchase_cols = [
    "InAppPurchaseAmount",
    "FirstPurchaseDaysAfterInstall",
    "PaymentMethod",
    "LastPurchaseDate"
]

In [18]:
df_clean[demographic_cols].isnull().sum()

Age          60
Gender       60
Country      60
Device       60
GameGenre    60
dtype: int64

In [19]:
df_clean[purchase_cols].isnull().sum()

InAppPurchaseAmount              136
FirstPurchaseDaysAfterInstall    136
PaymentMethod                    136
LastPurchaseDate                 136
dtype: int64

In [20]:
# Check shape
print("Shape:", df_clean.shape)

# Check duplicate UserIDs
print("Duplicate UserIDs:", df_clean["UserID"].duplicated().sum())

# Check missing values
print("\nMissing values:")
print(df_clean.isnull().sum())

# Check data types
print("\nData types:")
print(df_clean.dtypes)

Shape: (3024, 13)
Duplicate UserIDs: 0

Missing values:
UserID                             0
Age                               60
Gender                            60
Country                           60
Device                            60
GameGenre                         60
SessionCount                       0
AverageSessionLength               0
SpendingSegment                    0
InAppPurchaseAmount              136
FirstPurchaseDaysAfterInstall    136
PaymentMethod                    136
LastPurchaseDate                 136
dtype: int64

Data types:
UserID                                   object
Age                                     float64
Gender                                   object
Country                                  object
Device                                   object
GameGenre                                object
SessionCount                              int64
AverageSessionLength                    float64
SpendingSegment                          object
InAppPurchaseAmount                     float64
FirstPurchaseDaysAfterInstall           float64
PaymentMethod                            object
LastPurchaseDate                 datetime64[ns]
dtype: object

In [21]:
df_clean.to_csv('game_data_clean.csv', index=False)